// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvA6zJfSinMnp6kCXNuML6P-cuIiFvL0',
    appId: '1:9771174359:web:59798a4f2bf0fe43126392',
    messagingSenderId: '9771174359',
    projectId: 'groceryapp-35891',
    authDomain: 'groceryapp-35891.firebaseapp.com',
    storageBucket: 'groceryapp-35891.appspot.com',
    measurementId: 'G-8XGCN1PEHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1zdOCwWz4Ih9l9Fq8KCYLpU-m8jgmo1Y',
    appId: '1:9771174359:android:3412f5a12c572b5d126392',
    messagingSenderId: '9771174359',
    projectId: 'groceryapp-35891',
    storageBucket: 'groceryapp-35891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjIlJXwkxLIPmJwH2OuNLwEBVg2OqY-Pg',
    appId: '1:9771174359:ios:4fcaba96492a3c2d126392',
    messagingSenderId: '9771174359',
    projectId: 'groceryapp-35891',
    storageBucket: 'groceryapp-35891.appspot.com',
    iosClientId: '9771174359-1eok697f32m9cejsrbqntus9kgl511fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicNotesPlayerAppSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjIlJXwkxLIPmJwH2OuNLwEBVg2OqY-Pg',
    appId: '1:9771174359:ios:ab6f1e95a2f2199a126392',
    messagingSenderId: '9771174359',
    projectId: 'groceryapp-35891',
    storageBucket: 'groceryapp-35891.appspot.com',
    iosClientId: '9771174359-u9iagpeauebde38ii3j70rubs3o7jec0.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicNotesPlayerAppSetup.RunnerTests',
  );
}
